### ISSUE TITLE
cannot find apps/mainsite/settings_local.py.example

### ISSUE THREAD

**Issue by westudiodev** [edubadges/edubadges-server#80]
Hi，

when I try to start  the server follow the guide in README, I cannot find this file: 
apps/mainsite/settings_local.py.example

Is it missing when commit to github?

**Comment by oharsta** [comment]
We have a different way of bootstrapping the env variables. See https://github.com/edubadges/edubadges-server/blob/develop/env_vars.sh.example and https://github.com/edubadges/edubadges-server#customize-local-settings-to-your-environment
