### ISSUE TITLE
Requirements issue

### ISSUE THREAD

**Issue by baireslearn** [edubadges/edubadges-server#97]
File [requirements.txt](https://github.com/edubadges/edubadges-server/blob/develop/requirements.txt#L23) refers to two repositories that no longer exist:
- Line 21:  github.com/concentricsky/django-cachemodel
- Line 23:  github.com/concentricsky/django-basic-models

**Comment by 007ke** [comment]
Having trouble installing edubadges-server and edubadges-ui
Do you have any visual way of depicting the entire installation process using video or screen shots?
If not, can i contact you for some assistance?

**Comment by fransward** [comment]
We have included this code, which was no longer available on GitHub, into our repo's now:
https://github.com/edubadges/edubadges-server/commit/4963a6c53de635656f0fa7237a2dec157b313f42
